name: Run and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: stable

      - name: Run
        run: |
          deno task start

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "TropicalFish-data.zip,TropicalFish-resource.zip"
